WebApp/Models/ErrorViewModel.cs
namespace WebApp.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

WebApp/Controllers/PagoController.cs
using Microsoft.AspNetCore.Mvc;
using LogicaNegocio;
using WebApp.Filters;

namespace WebApp.Controllers;

[LoginFilter]
public class PagoController : Controller
{
    private Sistema sistema = Sistema.Instancia;

    public IActionResult Index()
    {
        string email = HttpContext.Session.GetString("Email");
        Usuario usuarioActual = sistema.ObtenerUsuarioPorEmail(email);
        
        if (HttpContext.Session.GetString("Rol") == Rol.EMPLEADO.ToString())
        {
            List<Pago> pagosMes = sistema.ObtenerPagosMesPorUsuario(email);
            pagosMes = sistema.OrdenarPagosPorMontoDesc(pagosMes);
            return View(pagosMes);
        }

        if (usuarioActual != null)
        {
            List<Pago> pagosEquipo = new List<Pago>(sistema.ObtenerPagosPorEquipo(usuarioActual.Equipo.Nombre));
            pagosEquipo = sistema.OrdenarPagosPorMontoDesc(sistema.ObtenerPagosMes((pagosEquipo)));
            return View(pagosEquipo);
        }
        
        return View();
    }

    public IActionResult AgregarPago(string mensaje)
    {
        if (mensaje != null && !string.IsNullOrEmpty(mensaje))
        {
            ViewBag.Mensaje = mensaje;
        }
        
        string email = HttpContext.Session.GetString("Email");
        Usuario usuario = sistema.ObtenerUsuarioPorEmail(email);
        ViewBag.Usuario = usuario;
        List<TipoDeGasto> tiposDeGastos = sistema.ObtenerTiposDeGastos();
        ViewBag.TiposDeGastos = tiposDeGastos;
        return View();
    }
    
    [HttpPost]
    public IActionResult AgregarPago
    (
        string Descripcion,
        double Monto,
        MetodoDePago MetodoDePago,
        string TipoPagoSeleccionado,
        string TipoDeGasto,
        DateTime FechaDesde,
        DateTime? FechaHasta,
        DateTime FechaPago,
        string NumeroRecibo)
    {
        try
        {
            Usuario usuario = sistema.ObtenerUsuarioPorEmail(HttpContext.Session.GetString("Email"));
            //Obtenemos el tipo de gasto por nombre
            TipoDeGasto encontrado = sistema.ObtenerTipoDeGastoPorNombre(TipoDeGasto);
            TipoDeGasto tipoDeGasto = new TipoDeGasto(encontrado.Nombre, encontrado.Descripcion);
            
            Pago nuevoPago;
            
            if (TipoPagoSeleccionado == "RECURRENTE")
            {
                nuevoPago = new Recurrente(
                    Descripcion,
                    Monto,
                    MetodoDePago,
                    tipoDeGasto,
                    usuario,
                    FechaDesde,
                    FechaHasta
                );

            }  else
            {
                nuevoPago = new Unico(
                    Descripcion,
                    Monto,
                    MetodoDePago,
                    tipoDeGasto,
                    usuario,
                    FechaPago,
                    NumeroRecibo
                );

            }
        
            sistema.AgregarPago(nuevoPago);
            TempData["Mensaje"] = "Pago cargado con éxito!";
            return RedirectToAction("Index");
        }
        catch (Exception e)
        {
            return RedirectToAction("AgregarPago", new { mensaje = e.Message });
        }
    }

    [GerenteFilter]
    public IActionResult FiltrarPorFecha(DateTime Fecha)
    {
        string email = HttpContext.Session.GetString("Email");
        Usuario usuarioActual = sistema.ObtenerUsuarioPorEmail(email);
        
        if (usuarioActual != null)
        {
            List<Pago> pagosFiltrados = new List<Pago>(sistema.ObtenerPagosPorEquipo(usuarioActual.Equipo.Nombre));
            pagosFiltrados = sistema.ObtenerPagosPorFecha(Fecha);
            return View("Index", pagosFiltrados);
        }

        return View();
    }
    
}

WebApp/Controllers/TipoDeGastoController.cs
using LogicaNegocio;
using Microsoft.AspNetCore.Mvc;
using WebApp.Filters;

namespace WebApp.Controllers;

[LoginFilter]
public class TipoDeGastoController : Controller
{
    private Sistema sistema = Sistema.Instancia;
    
    public IActionResult Index()
    {
        List<TipoDeGasto> tiposDeGastos = sistema.ObtenerTiposDeGastos();

        return View(tiposDeGastos);
    }

    [GerenteFilter]
    public IActionResult AgregarTipoDeGasto()
    {
        return View();
    }
    
    [HttpPost]
    public IActionResult AgregarTipoDeGasto(string Nombre, string Descripcion)
    {
        try
        {
            // Validar que no exista
            if (sistema.ObtenerTipoDeGastoPorNombre(Nombre) != null)
            {
                ViewBag.Mensaje = "Tipo de gasto ya existente";
                return View();
            }
            else
            {
                TipoDeGasto nuevo = new TipoDeGasto(Nombre, Descripcion);
                sistema.AgregarTipoDeGasto(nuevo);
                TempData["Mensaje"] = "Tipo de Gasto registrado con éxito";
            }
        }
        catch (Exception e)
        {
            ViewBag.Mensaje = "Datos inválidos";
            return View();
        }
        return RedirectToAction("Index");
    }

    [GerenteFilter]
    public IActionResult EliminarTipoDeGasto(string Nombre)
    {
        TipoDeGasto gasto =  sistema.ObtenerTipoDeGastoPorNombre(Nombre);
        if (gasto != null)
        {
        return View(gasto);
        }

        return RedirectToAction("Index");
    }
    
    [HttpPost]
    public IActionResult EliminarTipoDeGasto(string Nombre, string Descripcion)
    {
        try
        {
            List<Pago> pagosARecorrer = new List<Pago>(sistema.ObtenerPagos());
            TipoDeGasto gasto =  sistema.ObtenerTipoDeGastoPorNombre(Nombre);
            
            foreach (Pago pago in pagosARecorrer)
            {
                if (pago.TipoDeGasto.Nombre == Nombre && pago.TipoDeGasto.Descripcion == Descripcion)
                {
                    ViewBag.Mensaje = "No es posible eliminar este Tipo de Gasto.";
                    return View(gasto);
                }
            }

            sistema.EliminarTipoDeGastoPorNombre(Nombre);
            TempData["Mensaje"] = "Tipo de Gasto eliminado correctamente.";
        }
        catch (Exception e)
        {
            throw new Exception(e.Message);
        }
        return RedirectToAction("Index");
    }
}

WebApp/Controllers/UsuarioController.cs
using Microsoft.AspNetCore.Mvc;
using LogicaNegocio;
using WebApp.Filters;

namespace WebApp.Controllers;

public class UsuarioController : Controller
{
    private Sistema sistema = Sistema.Instancia;
    
    public IActionResult Login()
    {
        return View();
    }

    [HttpPost]
    public IActionResult Login(string Email, string Contrasena)
    {
        try
        {
            Usuario usuario = sistema.BuscarUsuario(Email, Contrasena);
            if (usuario != null)
            {
                HttpContext.Session.SetString("Email", usuario.Email);
                HttpContext.Session.SetString("Rol", usuario.Rol.ToString());
                TempData["Mensaje"] = "Logueado con éxito";
                return RedirectToAction("Perfil");
            }
            else
            {
                ViewBag.Mensaje = "Datos incorrectos";
            }
        }
        catch(Exception ex)
        {
            ViewBag.Mensaje = ex.Message;
        }

        return View();
    }

    [LoginFilter]
    public IActionResult Logout()
    {
        HttpContext.Session.Clear();
        return RedirectToAction("Login");
    }

    [LoginFilter]
    public IActionResult Perfil()
    {
        string email = HttpContext.Session.GetString("Email");
        
        if (email == null) return RedirectToAction("Login");
        
        Usuario usuario = sistema.ObtenerUsuarioPorEmail(email);
        
        List<Usuario> usuariosEquipo = sistema.ObtenerUsuariosPorEquipo(usuario.Equipo.Nombre);
        usuariosEquipo = sistema.OrdenarUsuariosEquipoPorEmailAsc(usuariosEquipo);
        ViewBag.Usuarios = usuariosEquipo;
        
        double totalGastadoMes = sistema.ObtenerTotalPagosMesPorUsuario(usuario.Email);
        ViewBag.TotalGastadoMes = totalGastadoMes;
        return View(usuario);
    }
}

WebApp/Views/Pago/AgregarPago.cshtml
@using LogicaNegocio
@model LogicaNegocio.Pago

<div class="d-flex flex-column gap-2 w-60 justify-content-center align-items-center border p-4">
    @if (ViewBag.Mensaje != null)
    {
        <span class="alert alert-danger text-center">@ViewBag.Mensaje</span>
    }

    <h2>Agregar Pago</h2>

    <form method="post" class="d-flex flex-column gap-2 mb-4 w-100 p-4">
        <div>
            <label  class="form-label">Tipo de pago</label>
            <select name="TipoPagoSeleccionado" class="form-control">
                <option value="RECURRENTE">RECURRENTE</option>
                <option value="UNICO">UNICO</option>
            </select>
        </div>
        <div class="mb-3">
            <label for="Descripcion" class="form-label">Descripcion</label>
            <input type="text" class="form-control" name="Descripcion" placeholder="Ej: Wi-Fi para las oficinas" required>
        </div>
        <div class="mb-3">
            <label for="Monto" class="form-label">Monto</label>
            <input type="number" class="form-control" name="Monto" min="1" placeholder="Ej: 2200" required>
        </div>
        <div class="mb-3">
            <label class="form-label" for="MetodoDePago"> Método de pago</label>
            <select class="form-control" name="MetodoDePago">
                <option value="@MetodoDePago.CREDITO">CREDITO</option>
                <option value="@MetodoDePago.DEBITO">DEBITO</option>
                <option value="@MetodoDePago.EFECTIVO">EFECTIVO</option>
            </select>
        </div>
        <div class="mb-3">
            <label for="TipoDeGasto" class="form-label">Tipo de Gasto</label>
            <select name="TipoDeGasto" class="form-control">
                @foreach (TipoDeGasto tGasto in ViewBag.TiposDeGastos)
                {
                    <option value="@tGasto.Nombre">@tGasto.Nombre - <span>@tGasto.Descripcion</span></option>
                }
            </select>
        </div>
        <div>
            <label for="Usuario" class="form-label">Usuario</label>
            <input type="text" class="form-control" name="Usuario" value="@ViewBag.Usuario.Email" readonly>
        </div>
    
        <div id="campos-recurrente">
            <div class="mb-3">
                <label for="FechaDesde" class="form-label">Fecha Desde</label>
                <input type="date" class="form-control" name="FechaDesde" value="@DateTime.Now.ToString("yyyy-MM-dd")" readonly>
            </div>

            <div class="mb-3">
                <label for="FechaHasta" class="form-label">Fecha Hasta</label>
                <input type="date" class="form-control" name="FechaHasta">
            </div>
        </div>
    
        <div id="campos-unico" style="display:none;">
            <div class="mb-3">
                <label for="FechaPago" class="form-label">Fecha de Pago</label>
                <input type="date" class="form-control" name="FechaPago" value="@DateTime.Now.ToString("yyyy-MM-dd")" readonly>
            </div>

            <div class="mb-3">
                <label for="NumeroRecibo" class="form-label">Número de Recibo</label>
                <input type="text" class="form-control" name="NumeroRecibo">
            </div>
        </div>

        <script>
    document.querySelector("select[name='TipoPagoSeleccionado']")
        .addEventListener("change", function() {
            const camposUnico = document.getElementById("campos-unico");
            const camposRecurrente = document.getElementById("campos-recurrente");

            const inputNumeroRecibo = camposUnico.querySelector("input[name='NumeroRecibo']");

            if (this.value === "UNICO") {
                camposUnico.style.display = "block";
                inputNumeroRecibo.setAttribute("required", "required")
                camposRecurrente.style.display = "none";
                
            } else {
                camposUnico.style.display = "none";
                inputNumeroRecibo.removeAttribute("required");
                camposRecurrente.style.display = "block";
            }
        });
    </script>

        <button type="submit" class="btn btn-primary">Agregar</button>
    </form>
</div>

WebApp/Views/Pago/Index.cshtml
@using LogicaNegocio
@model IEnumerable<Pago>

<div class="d-flex flex-column gap-2 p-2">
    @{
        <h1>
            @(Context.Session.GetString("Rol") == Rol.GERENTE.ToString() ? "Pagos" : "Mis pagos mensuales")
        </h1>
    }
    @if (TempData["Mensaje"] != null)
    {
        <span class="alert alert-info text-center">@TempData["Mensaje"]</span>
    }
    @if (Model != null && Model.Count() > 0)
    {
        <table class="table table-dark table-hover">
            <thead>
            @if (Context.Session.GetString("Rol") == Rol.GERENTE.ToString())
            {
                <tr>
                    <td colspan="4">
                        <form action="/Pago/FiltrarPorFecha" class="d-flex justify-content-end align-items-center gap-2">
                            <div class="form-label m-0">
                                <input type="date" name="Fecha" class="form-control " required/>
                            </div>
                            <input type="submit" value="Filtrar" class="btn btn-primary"/>
                        </form>
                    </td>
                </tr>
            }
            <tr>
                <th>Id</th>
                <th>Descripcion</th>
                <th>Usuario</th>
                <th>Costo</th>
            </tr>
            </thead>
            <tbody>
            @foreach (Pago pago in Model)
            {
                <tr>
                    <td>@pago.Id</td>
                    <td>@pago.Descripcion</td>
                    <td>@pago.Usuario.Email</td>
                    <td>$@pago.CostoMostrar</td>
                </tr>
            }
            </tbody>
        </table>
        <a href="~/Pago/AgregarPago"><input type="button" value="Cargar Pago" class="btn btn-primary"/> </a>
    }
    else
    {
        <span class="alert alert-info text-center mt-2">No existen pagos para la fecha seleccionada...</span>
    }
</div>

WebApp/Views/Shared/_Layout.cshtml
@using LogicaNegocio
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - Gestor Pagos V1</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true"/>
    <link rel="stylesheet" href="~/WebApp.styles.css" asp-append-version="true"/>
</head>
<body>
<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
        <div class="container-fluid">
            @if (Context.Session.GetString("Email") == null)
            {
            <a class="navbar-brand" asp-area="" asp-controller="Usuario" asp-action="Login">Gestor Pagos V1</a>
            }
            else
            {
            <a class="navbar-brand" asp-area="" asp-controller="Usuario" asp-action="Perfil">Gestor Pagos V1</a>
            }
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    @if (Context.Session.GetString("Email") == null)
                    {
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Usuario" asp-action="Login">Login</a>
                        </li>
                    }
                    else if (Context.Session.GetString("Email") != null && Context.Session.GetString("Rol") == Rol.GERENTE.ToString())
                    {
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Usuario" asp-action="Perfil">Perfil</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Pago" asp-action="Index">Pagos</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="TipoDeGasto" asp-action="Index">Tipo de Gastos</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Usuario" asp-action="Logout">Logout</a>
                        </li>
                    }
                    else
                    {
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Usuario" asp-action="Perfil">Perfil</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Pago" asp-action="Index">Pagos mensuales</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Usuario" asp-action="Logout">Logout</a>
                        </li>
                    }
                </ul>
            </div>
        </div>
    </nav>
</header>
<div class="container">
    <main role="main" class="pb-3">
        @RenderBody()
    </main>
</div>

<footer class="border-top footer text-muted">
    <div class="container text-center">
        &copy; 2025 - Gestor Pagos V1 - <a href="https://github.com/facundoms284/gestion-de-pagos" target="_blank" class="text-decoration-none">GitHub</a>
    </div>
</footer>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
@await RenderSectionAsync("Scripts", required: false)
</body>
</html>

WebApp/Views/TipoDeGasto/AgregarTipoDeGasto.cshtml
@using LogicaNegocio
@model LogicaNegocio.TipoDeGasto

<div class="d-flex flex-column gap-2 w-60 justify-content-center align-items-center border p-4">
    <h2>Agregar Gasto</h2>
    
    <form method="post" class="d-flex flex-column gap-2 mb-4 p-4 w-100">
        <div>
            <label for="Nombre" class="form-label">Nombre</label>
            <input type="text" class="form-control" name="Nombre"required>
        </div>
        <div class="mb-3">
            <label for="Descripcion" class="form-label">Descripcion</label>
            <input type="text" class="form-control" name="Descripcion" required>
        </div>

        <button type="submit" class="btn btn-primary">Agregar</button>
    </form>
    @if (ViewBag.Mensaje != null)
    {
        <span class="alert alert-danger text-center">@ViewBag.Mensaje</span>
    }
</div>

WebApp/Views/TipoDeGasto/EliminarTipoDeGasto.cshtml
@using LogicaNegocio
@model LogicaNegocio.TipoDeGasto

<div class="d-flex flex-column gap-2 w-60 justify-content-center align-items-center border p-4">
    <h2>Eliminar Gasto</h2>

    <form method="post" class="d-flex flex-column gap-2 p-4 w-100">
        <div>
            <label for="Nombre" class="form-label">Nombre</label>
            <input type="text" class="form-control" name="Nombre" value="@Model.Nombre" readonly>
        </div>
        <div>
            <label for="Descripcion" class="form-label">Descripcion</label>
            <input type="text" class="form-control" name="Descripcion" value="@Model.Descripcion" readonly>
        </div>
        <button type="submit" class="btn btn-danger">Eliminar</button>
    </form>

    @if (ViewBag.Mensaje != null)
    {
        <span class="alert alert-danger text-center">@ViewBag.Mensaje</span>
    }
</div>

WebApp/Views/TipoDeGasto/Index.cshtml
@using LogicaNegocio;
@model IEnumerable<TipoDeGasto>
<div class="d-flex flex-column gap-2">
    @if (TempData["Mensaje"] != null)
    {
        <span class="alert alert-info m-2 text-center">
            @TempData["Mensaje"]
        </span>
    }
    <h1>Tipos de gastos</h1>

    <table class="table table-dark table-hover">
        <thead>
        <tr>
            <th>Nombre</th>
            <th>Descripción</th>
            <th></th>
        </tr>
        </thead>
        <tbody>
        @foreach (TipoDeGasto tipoDeGasto in Model)
        {
            <tr>
                <td>@tipoDeGasto.Nombre</td>
                <td>@tipoDeGasto.Descripcion</td>
                <td class="mt-4">
                    <a asp-controller="TipoDeGasto"
                       asp-action="EliminarTipoDeGasto"
                       asp-route-Nombre="@tipoDeGasto.Nombre">
                        <input type="button" value="Eliminar" class="btn btn-danger"/>
                    </a>
                </td>
            </tr>
        }
        </tbody>
    </table>

    <a href="~/TipoDeGasto/AgregarTipoDeGasto"><input type="button" value="Cargar Gasto" class="btn btn-primary"/> </a>
</div>

WebApp/Views/Usuario/Login.cshtml
@{
    ViewData["Title"] = "Login";
}

<div class="d-flex justify-content-center align-items-center">
    <div class="w-100 p-4 border" style="max-width: 50%;">
    <h1 class="text-center">Login</h1>
    @if (!string.IsNullOrEmpty(ViewBag.Mensaje))
    {
        <div class="alert alert-danger text-center">
            @ViewBag.Mensaje
        </div>
    }

    <form method="post">
        <div class="mb-3">
            <label>Email</label>
            <input type="text" class="form-control" name="Email" required>
        </div>
        <div class="mb-3">
            <label>Contraseña</label>
            <input type="password" class="form-control" name="Contrasena" required>
        </div>
        <button type="submit" class=" btn btn-primary">Login</button>
    </form>
    </div>
</div>

WebApp/Views/Usuario/Perfil.cshtml
@using LogicaNegocio
@model LogicaNegocio.Usuario

@{
    ViewData["Title"] = "Perfil";
}

<div class="d-flex flex-column gap-2">
    
    @if (TempData["Mensaje"] != null)
    {
        <span class="alert alert-info text-center">
            @TempData["Mensaje"]
        </span>
    }

    <h1>Perfil</h1>

    <table class="table table-dark table-hover">
        <thead>
        <tr>
            <th>Rol</th>
            <th>Nombre</th>
            <th>Apellido</th>
            <th>Email</th>
            <th>Fecha Incorporación</th>
            <th>Equipo</th>
            <th>Total gastado este mes</th>
        </tr>
        </thead>
        <tbody>
        <tr>
        <td>@Model.Rol</td>
        <td>@Model.Nombre</td>
        <td>@Model.Apellido</td>
        <td>@Model.Email</td>
        <td>@Model.FechaIncorporacion.ToString("dd/MM/yyyy")</td>
        <td>@Model.Equipo.Nombre</td>
        <td>$@ViewBag.TotalGastadoMes</td>
        </tbody>
    </table>

    @if (Context.Session.GetString("Rol") == Rol.GERENTE.ToString())
    {
        <h2>Usuarios del equipo</h2>
        List<Usuario> usuariosEquipo = ViewBag.Usuarios;

        @if (usuariosEquipo != null && usuariosEquipo.Count > 0)
        {
            <table class="table table-dark table-hover">
                <thead>
                <tr>
                    <th>Email</th>
                    <th>Nombre Completo</th>
                    <th>Fecha Incorporación</th>
                </tr>
                </thead>
                <tbody>
                @foreach (Usuario usuario in usuariosEquipo)
                {
                    <tr>
                        <td>@usuario.Email</td>
                        <td>@usuario.Nombre @usuario.Apellido</td>
                        <td>@usuario.FechaIncorporacion.ToString("dd/MM/yyyy")</td>
                    </tr>
                }
                </tbody>
            </table>
        }
        else
        {
            <p>No hay otros usuarios en este equipo registrados.</p>
        }
    }
</div>